# Generated by Django 3.0.1 on 2019-12-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.EmailField(max_length=254, verbose_name='GMAILアドレス')),
                ('password', models.CharField(max_length=15, verbose_name='password')),
            ],
        ),
    ]
